image: maven:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    - mvn clean test

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    paths:
      - dist/*.jar